Update pr-validation.yaml

diff --git a/pr-validation.yaml b/pr-validation.yaml
--- a/pr-validation.yaml
+++ b/pr-validation.yaml
@@ -1,14 +1,29 @@
 name: Validar Origen de PR
+
 on:
   pull_request:
     branches: [main, dev]
+
 jobs:
   verify-origin-branch:
     runs-on: ubuntu-latest
     steps:
-      - name: Validar Main
-        if: github.base_ref == 'main' && github.head_ref != 'dev'
-        run: exit 1
-      - name: Validar Dev
-        if: github.base_ref == 'dev' && github.head_ref != 'test'
-        run: exit 1
+      - name: Validar si el PR va a Main
+        if: github.base_ref == 'main'
+        run: |
+          if [ "${{ github.head_ref }}" != "dev" ]; then
+            echo "ERROR: Los PRs a 'main' SOLO pueden venir de 'dev'. Origen actual: ${{ github.head_ref }}"
+            exit 1
+          else
+            echo "Origen válido: dev -> main."
+          fi
+
+      - name: Validar si el PR va a Dev
+        if: github.base_ref == 'dev'
+        run: |
+          if [ "${{ github.head_ref }}" != "test" ]; then
+            echo "ERROR: Los PRs a 'dev' SOLO pueden venir de 'test'. Origen actual: ${{ github.head_ref }}"
+            exit 1
+          else
+            echo "Origen válido: test -> dev."
+          fi
